server:
  port: 7300

spring:
  application:
    name: user-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-service
  cloud:
    bus:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: refresh


